In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pickle

pickle_file_path = "/content/drive/MyDrive/final_sam.pkl"
with open(pickle_file_path,'rb') as f:
  data = pickle.load(f)

print(data[0])

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


FileNotFoundError: ignored

In [ ]:
import re

for idx, val in enumerate(data):
  data[idx]['origin_lang'] = re.sub('[^a-zA-Z]', '', val['origin_lang']).strip()

# # 중복을 제거한 결과를 저장할 리스트
# filtered_data = []

# # 중복된 값을 저장하기 위한 set
# unique_origin_lang = set()

# for entry in data:
#     origin_lang = entry['origin_lang']
#     if origin_lang not in unique_origin_lang:
#         unique_origin_lang.add(origin_lang)
#         filtered_data.append(entry)

# print(filtered_data)


In [61]:
!pip install jamo

In [62]:
from jamo import h2j, j2hcj

def jamo(txt):
  return [_ for _ in j2hcj(h2j(txt))]


In [ ]:
src = []
trg = []

# for idx, val in enumerate(filtered_data):
#   src.append([val['origin_lang']])

# trg = [[char for word in wordlist['pronun_list'] for char in word] for wordlist in filtered_data]

for idx, val in enumerate(data):
  src.append([val['origin_lang']])

trg = [[char for word in wordlist['pronun_list'] for char in word] for wordlist in data]

TypeError: ignored

In [63]:
import json

src = []
trg = []

with open('/content/drive/MyDrive/final_sam.txt', 'r') as f:
    for line in f:
        data = json.loads(line)
        src.append(data['origin_lang'])
        trg.append(data['pronun_list'])

print("src:", src)
print("trg:", trg)



src: ['AA', 'AAA', 'AAAC', 'AAC', 'AACM', 'AACSR', 'AAD', 'AADT', 'AAF', 'AAI', 'AALA', 'AAM', 'AARE', 'AARQ', 'AAU', 'AB', 'ABA', 'ABB', 'ABC', 'ABCP', 'ABDR', 'ABEDA', 'ABG', 'ABIOS', 'ABM', 'ABO', 'ABR', 'ABS', 'ABSPDU', 'ABSTB', 'ABSTRIPS', 'ABU', 'ABX', 'AC', 'ACAP', 'ACAR', 'ACATS', 'ACB', 'ACC', 'ACD', 'ACE', 'ACELP', 'ACEPT', 'ACF', 'ACH', 'ACI', 'ACIA', 'ACK', 'ACL', 'ACM', 'ACN', 'ACO', 'ACP', 'ACPI', 'ACQ', 'ACR', 'ACRS', 'ACS', 'ACSA', 'ACSC', 'ACSE', 'ACSI', 'ACSR', 'ACST', 'ACT', 'ACTE', 'ACTH', 'ACTP', 'ACTV', 'ACU', 'ACV', 'AD', 'ADAPT', 'ADAS', 'ADAT', 'ADB', 'ADC', 'ADCCP', 'ADCON', 'ADCP', 'ADD', 'ADE', 'ADEX', 'ADF', 'ADFAED', 'ADH', 'ADHD', 'ADI', 'ADIBA', 'ADIS', 'ADIZ', 'ADL', 'ADM', 'ADMD', 'ADP', 'ADPCM', 'ADPE', 'ADPS', 'ADR', 'ADSL', 'ADSR', 'ADT', 'ADW', 'AE', 'AEBS', 'AEC', 'AED', 'AEI', 'AEL', 'AEM', 'AEO', 'AEP', 'AES', 'AESA', 'AEW', 'AF', 'AFA', 'AFAS', 'AFB', 'AFC', 'AFCEA', 'AFCI', 'AFCS', 'AFD', 'AFDB', 'AFESD', 'AFG', 'AFL', 'AFM', 'AFO', 'AFP', 'AF

In [64]:
print(trg[-1])
print(src[-1])

힙허거스팬티
hiphuggerspanties


In [65]:
korean_char = [char for word in trg for char in word]
korean_char_unique = list(sorted(set(korean_char)))


In [66]:
## Ready for data Pre-Processing
space = [' ']
pad = ['<pad>']
_and = ['&']
# Prepare English Data
big = [chr(i) for i in range(ord('A'), ord('Z')+1)]
small = [chr(i) for i in range(ord('a'), ord('z')+1)]

english_letter_list = pad + big + small + space + _and

idx2english = dict(enumerate(english_letter_list, 0))
english2idx = {v:k  for k,v in idx2english.items()}


# Prepare Korean Data
consonants = [chr(letter) for letter in range(ord('가'), ord('힣')+1)]
# vowel = [chr(letter) for letter in range(ord('ㅏ'), ord('ㅣ')+1)]

korean_letter_list = pad + korean_char_unique +  space

# Make a mapping with index
idx2korean = dict(enumerate(korean_letter_list, 0))
korean2idx = {v: k for k, v in idx2korean.items()}

print(len(english_letter_list))
print(len(korean_letter_list))

55
1079


In [67]:
import copy

src2idx = []
src2idx = [[english2idx[char] for word in wordlist for char in word] for wordlist in src]


trg2idx = []
trg2idx = [[korean2idx[char] for word in wordlist for char in word] for wordlist in trg]

src2idx_ = []
trg2idx_ = []
for idx, value in enumerate(src2idx):
  if len(src2idx[idx]) <= 30:
      src2idx_.append(value)
      trg2idx_.append(trg2idx[idx])


src2idx = src2idx_
trg2idx = trg2idx_
num_10 = 0
num_20 = 0
num_30 = 0
num_40 = 0
num_40_over = 0
for idx, value in enumerate(src2idx):
  if len(src2idx[idx]) <= 10:
    num_10 += 1
  elif len(src2idx[idx]) <= 20:
    num_20 += 1
  elif len(src2idx[idx]) <= 30:
    num_30 += 1
  elif len(src2idx[idx]) <= 40:
    num_40 += 1
  elif len(src2idx[idx]) > 40:
    num_40_over += 1

print(f"num_10 : {num_10}, num_20 : {num_20}, num_30: {num_30}, num_40 : {num_40}, num_40_over : {num_40_over}")

src2idx_reverse = copy.deepcopy(src2idx) # 단어 벡터를 lstm에 거꾸로 집어넣었을 때, 정확도를 보기 위해서 만듬

max_len_src = max(len(src2idx_list) for src2idx_list in src2idx)
max_len_trg = max(len(trg2idx_list) for trg2idx_list in trg2idx)


print(max_len_src)
print(max_len_trg)

num_10 : 38091, num_20 : 24690, num_30: 1157, num_40 : 0, num_40_over : 0
30
17


In [68]:
def padding(st_list, max_length, is_trg):
  # if is_trg == True:
  for tmp_list in st_list:
    while len(tmp_list) < max_length:
      tmp_list.append(0)
  # else:
  #   for tmp_list in st_list:
  #     while len(tmp_list) < max_length + 2:
  #       tmp_list.append(0)

padding(src2idx, max_len_src, False)
padding(trg2idx, max_len_trg, True)

src_size = len(src2idx)
trg_size = len(trg2idx)

src2idx_tensorflow = src2idx
trg2idx_tensorflow = trg2idx

src2idx_tensorflow_reverse = src2idx_reverse # 역변환


In [ ]:
# # 리스트 역

# import numpy as np

# X = src2idx_tensorflow_reverse
# y = trg2idx_tensorflow
# padding(X, max_len_src, False)
# z = []
# print(X[0])
# print(len(X[0]))
# for idx, val in enumerate(X):
#   z.append(val[::-1])
# X = z
# X = np.array(X)
# y = np.array(y)

# print(X[:50])



[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
20
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  1  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 13  3  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 18 19  3  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  4  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 20  4  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 12  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 13  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5 18  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 17 18  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 2

In [69]:
import numpy as np

X = src2idx_tensorflow
y = trg2idx_tensorflow

X = np.array(X)
y = np.array(y)


print(y[:5])

print(y.shape)


[[590 668 590 668   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [590 668 590 668 590 668   0   0   0   0   0   0   0   0   0   0   0]
 [590 668 590 668 590 668 533   0   0   0   0   0   0   0   0   0   0]
 [590 668 590 668 533   0   0   0   0   0   0   0   0   0   0   0   0]
 [590 668 590 668 533 594   0   0   0   0   0   0   0   0   0   0   0]]
(63938, 17)


In [ ]:
from keras.layers.rnn import Bidirectional
from keras.utils import np_utils
num_classes = len(korean_letter_list)
# y = np_utils.to_categorical(y, num_classes=num_classes).reshape(y.shape[0], y.shape[1], num_classes)
print(X.shape)
print(y.shape)
## Split train & test & validation set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.5)


# Parameters for the model and dataset
HIDDEN_SIZE = 256
BATCH_SIZE = 32
LAYERS = 2
MAX_EPOCHS = 100
EMBEDDING_OUTPUT_SIZE = 512
DROPOUT_RATE = 0.20


stop_monitor = 'val_loss'
stop_delta = 0
stop_epochs = 10


# ## Build Model
import tensorflow as tf
from keras.models import Sequential, load_model
from keras.layers import Dense, TimeDistributed, Activation, RepeatVector, Embedding, LSTM, Masking, Dropout



print('Build Model...')

model = Sequential()

model.add(Embedding(
    input_dim=len(english_letter_list),  # 단어 갯수 + padding (1)
    output_dim=EMBEDDING_OUTPUT_SIZE,  # 출력 벡터
    input_length=X.shape[1],  # 입력 길이
    mask_zero = True
))

model.add(Bidirectional(LSTM(HIDDEN_SIZE // 2, return_sequences=True, input_shape=(X.shape[1], ))))
model.add(Bidirectional(LSTM(HIDDEN_SIZE // 2)))

model.add(RepeatVector(y.shape[1]))  # Maximum output length

for _ in range(LAYERS):
    model.add(LSTM(HIDDEN_SIZE, return_sequences=True))
    model.add(Dropout(DROPOUT_RATE))

model.add(TimeDistributed(Dense(len(korean_letter_list))))
model.add(Activation('softmax'))

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)


model.summary()
print('Done')

# Callbacks
from keras.callbacks import EarlyStopping, ModelCheckpoint



callbacks_list = [
    EarlyStopping(
        monitor=stop_monitor,
        min_delta=stop_delta,
        patience=stop_epochs,
        verbose=1,
        mode='auto',
    ),
    ModelCheckpoint(filepath="/content/drive/MyDrive/256_512_32_best.h5",
        monitor=stop_monitor,
        save_best_only=True,
        verbose=1,
        mode='auto',)
]
hist = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    batch_size=BATCH_SIZE,
    epochs=MAX_EPOCHS,
    verbose=1,
    callbacks=callbacks_list
)
# for i in range(10):
#   hist = model.fit(
#     X_train, y_train,
#     validation_data=(X_val, y_val),
#     batch_size=BATCH_SIZE,
#     epochs=MAX_EPOCHS,
#     verbose=1,
#     callbacks=callbacks_list
# )


## Visualize history



loss, acc = model.evaluate(X_test, y_test)


print()
print("Last Model: ")
print('Loss: %.2f' % loss)
print('Accuracy: %.2f' % acc)

import matplotlib.pyplot as plt

epochs = range(1, len(hist.history['accuracy']) + 1)
plt.plot(epochs, hist.history['loss'])
plt.plot(epochs, hist.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

model.save('drive/MyDrive/256_512_32_temp.h5')


(63938, 30)
(63938, 17)
Build Model...
Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 30, 512)           28160     
                                                                 
 bidirectional_12 (Bidirecti  (None, 30, 256)          656384    
 onal)                                                           
                                                                 
 bidirectional_13 (Bidirecti  (None, 256)              394240    
 onal)                                                           
                                                                 
 repeat_vector_6 (RepeatVect  (None, 17, 256)          0         
 or)                                                             
                                                                 
 lstm_26 (LSTM)              (None, 17, 256)           525312    
               

In [ ]:
model.save('drive/MyDrive/my_model_word_reverse.h5')

In [ ]:
!pip install hangul_utils

INFO: pip is looking at multiple versions of hangul-utils to determine which version is compatible with other requirements. This could take a while.
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
# 모델 로드
model = tf.keras.models.load_model("/content/drive/MyDrive/my_model_word_temp2.h5")



In [ ]:
import numpy as np
def eng2idx(str1):
  str2idx = [char for char in str1]
  str2idx1 = [english2idx[char] for char in str2idx]
  while len(str2idx1) < max_len_src:
    str2idx1.append(0)

  return [str2idx1]

from keras.models import load_model

def one_hot2idx(model, str):
  predic = model.predict(eng2idx(str))
  predic_char = predic[0][0]
  _idx2korean = []
  for idx, val in enumerate(predic[0]):
    max_index = np.argmax(val)
    _idx2korean.append(max_index)

  idx2korean_ = [idx2korean[idx] for idx in _idx2korean if idx != 0]

  return idx2korean_
print(one_hot2idx(model, "b"))
print(one_hot2idx(model, "haribo"))
print(one_hot2idx(model, "jonna"))
print(one_hot2idx(model, "fuck"))
print(one_hot2idx(model, "you"))
print(one_hot2idx(model, "bitch"))
print(one_hot2idx(model, "mega"))
print(one_hot2idx(model, "samsung"))
print(one_hot2idx(model, "hyundai"))
print(one_hot2idx(model, "homerunball"))
print(one_hot2idx(model, "control"))
print(one_hot2idx(model, "wori"))
print(one_hot2idx(model, "once"))
print(one_hot2idx(model, "twice"))
print(one_hot2idx(model, "sexily"))
print(one_hot2idx(model, "halabozi"))
print(one_hot2idx(model, "multiheadattention"))
print(one_hot2idx(model, "whitecotton"))
print(one_hot2idx(model, "breakingdrive"))
print(one_hot2idx(model, "multilayersequence"))
print(one_hot2idx(model, "pingping"))
print(one_hot2idx(model, "creative"))
print(one_hot2idx(model, "sequencediagram"))

1/1 [==============================] - 7s 7s/step
['비']
1/1 [==============================] - 0s 43ms/step
['하', '리', '보']
1/1 [==============================] - 0s 42ms/step
['조', '나']
1/1 [==============================] - 0s 44ms/step
['퍽']
1/1 [==============================] - 0s 53ms/step
['유']
1/1 [==============================] - 0s 45ms/step
['비', '치']
1/1 [==============================] - 0s 44ms/step
['메', '가']
1/1 [==============================] - 0s 48ms/step
['샘', '송']
1/1 [==============================] - 0s 42ms/step
['힌', '데', '이']
1/1 [==============================] - 0s 42ms/step
['홈', '런', '볼']
1/1 [==============================] - 0s 41ms/step
['컨', '트', '롤']
1/1 [==============================] - 0s 41ms/step
['루', '리']
1/1 [==============================] - 0s 43ms/step
['온', '스']
1/1 [==============================] - 0s 44ms/step
['트', '와', '이', '스']
1/1 [==============================] - 0s 44ms/step
['섹', '실', '리']
1/1 [==============================] 

In [ ]:
import numpy as np
def eng2idx(str1):
  str2idx = [char for char in str1]
  str2idx1 = [english2idx[char] for char in str2idx]
  str2idx2 = str2idx1[::-1]
  while len(str2idx2) < max_len_src:
    str2idx2.append(0)
  return [str2idx2]

from keras.models import load_model

def one_hot2idx(model, str):
  predic = model.predict(eng2idx(str))
  predic_char = predic[0][0]
  _idx2korean = []
  for idx, val in enumerate(predic[0]):
    max_index = np.argmax(val)
    _idx2korean.append(max_index)

  idx2korean_ = [idx2korean[idx] for idx in _idx2korean if idx != 0]

  return ''.join(idx2korean_)
print(one_hot2idx(model, "haribo"))
print(one_hot2idx(model, "jonna"))
print(one_hot2idx(model, "fuck"))
print(one_hot2idx(model, "you"))
print(one_hot2idx(model, "bitch"))
print(one_hot2idx(model, "mega"))
print(one_hot2idx(model, "samsung"))
print(one_hot2idx(model, "hyundai"))
print(one_hot2idx(model, "homerunball"))
print(one_hot2idx(model, "control"))
print(one_hot2idx(model, "wori"))
print(one_hot2idx(model, "once"))
print(one_hot2idx(model, "twice"))
print(one_hot2idx(model, "sexily"))
print(one_hot2idx(model, "halabozi"))
print(one_hot2idx(model, "karaoke"))
print(one_hot2idx(model, "multiheadattention"))
print(one_hot2idx(model, "whitecotton"))


1/1 [==============================] - 0s 39ms/step
고자이마우


In [ ]:
!pip install eng-to-ipa

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 14.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for eng-to-ipa: filename=eng_to_ipa-0.0.2-py3-none-any.whl size=2822607 sha256=1bb0a4043643737509dbe3b0051ebb5fb627792588378c6f4881d7566a2eaba3
  Stored in directory: /root/.cache/pip/wheels/5b/ab/07/fe6722f710d8ef8bd0ccb4eb689ef96f5552f3fc0c80c1aa9c
Successfully built eng-to-ipa


In [ ]:
import eng_to_ipa as ipa

apple = ipa.convert("")
print(apple)

kaiti*
