In [ ]:
import re

def extract_alpha_words_from_file(file_path):
    alpha_words = []

    with open(file_path, 'r') as file:
        for line in file:
            words = line.split()
            for word in words:
                # 정규식을 사용하여 알파벳으로만 이루어진 단어를 추출
                alpha_word = re.sub(r'[^a-zA-Z]', '', word)
                if alpha_word:
                    alpha_words.append(alpha_word)

    return alpha_words

def save_alpha_words_to_file(alpha_words, output_file_path):
    with open(output_file_path, 'w') as file:
        for word in alpha_words:
            file.write(word + '\n')

input_file_path = '/content/eng_source.txt'  # 실제 파일 경로로 변경해주세요.
output_file_path = '/content/eng_source_alpha.txt'  # 실제 출력 파일 경로로 변경해주세요.

alpha_words = extract_alpha_words_from_file(input_file_path)
save_alpha_words_to_file(alpha_words, output_file_path)

print("알파벳 단어가 저장되었습니다.")


알파벳 단어가 저장되었습니다.


In [ ]:
import pickle

def merge_pickles(file1, file2, output_file):
    # Load data from the first pickle file
    with open(file1, 'rb') as f1:
        data1 = pickle.load(f1)

    # Load data from the second pickle file
    with open(file2, 'rb') as f2:
        data2 = pickle.load(f2)

    # Create a dictionary to store merged data
    merged_data = {}

    # Add data from the first pickle file to merged_data
    for item in data1:
        origin_lang = item['origin_lang']
        if origin_lang not in merged_data:
            merged_data[origin_lang] = item

    # Add data from the second pickle file to merged_data
    for item in data2:
        origin_lang = item['origin_lang']
        if origin_lang not in merged_data:
            merged_data[origin_lang] = item

    # Save the merged data to the output pickle file
    with open(output_file, 'wb') as output_f:
        pickle.dump(list(merged_data.values()), output_f)

# Paths to the input pickle files and the output merged pickle file
pickle_file1 = '/content/eng_database.pkl'
pickle_file2 = '/content/sorted_eng_data.pkl'
output_pickle_file = '/content/merged_eng.pkl'

# Call the merge_pickles function to merge the pickle files
merge_pickles(pickle_file1, pickle_file2, output_pickle_file)

print("Pickle files merged successfully!")


Pickle files merged successfully!


In [ ]:
import pickle

# pickle 파일 읽기
input_filename = '/content/merged_eng.pkl'
output_filename = '/content/output.txt'

try:
    with open(input_filename, 'rb') as f:
        data = pickle.load(f)
except FileNotFoundError:
    print(f"{input_filename} 파일을 찾을 수 없습니다.")
    exit()

# 읽어온 데이터를 txt 파일로 저장
try:
    with open(output_filename, 'w') as f:
        f.write(str(data))
    print(f"{output_filename} 파일로 데이터를 저장했습니다.")
except Exception as e:
    print(f"파일 저장 중 오류가 발생했습니다: {e}")

/content/output.txt 파일로 데이터를 저장했습니다.


In [ ]:
import pickle

pickle_file_path = "/content/merged_eng.pkl"
with open(pickle_file_path,'rb') as f:
  data = pickle.load(f)

print(data[10])

{'origin_lang': 'garnet', 'pronun_list': '가닛'}


In [ ]:
data_alp = [
            ('에이', '외래어', '어휘', None, '에이', None, '일반어', '명사', 'A', None),
            ('에이', '외래어', '어휘', None, '에이', None, '일반어', '명사', 'a', None),
            ('비', '외래어', '어휘', None, '비', None, '일반어', '명사', 'B', None),
            ('비', '외래어', '어휘', None, '비', None, '일반어', '명사', 'b', None),
            ('시', '외래어', '어휘', None, '시', None, '일반어', '명사', 'C', None),
            ('시', '외래어', '어휘', None, '시', None, '일반어', '명사', 'c', None),
            ('디', '외래어', '어휘', None, '디', None, '일반어', '명사', 'D', None),
            ('디', '외래어', '어휘', None, '디', None, '일반어', '명사', 'd', None),
            ('이', '외래어', '어휘', None, '이', None, '일반어', '명사', 'E', None),
            ('이', '외래어', '어휘', None, '이', None, '일반어', '명사', 'e', None),
            ('에프', '외래어', '어휘', None, '에프', None, '일반어', '명사', 'F', None),
            ('에프', '외래어', '어휘', None, '에프', None, '일반어', '명사', 'f', None),
            ('지', '외래어', '어휘', None, '지', None, '일반어', '명사', 'G', None),
            ('지', '외래어', '어휘', None, '지', None, '일반어', '명사', 'g', None),
            ('에이치', '외래어', '어휘', None, '에이치', None, '일반어', '명사', 'H', None),
            ('에이치', '외래어', '어휘', None, '에이치', None, '일반어', '명사', 'h', None),
            ('아이', '외래어', '어휘', None, '아이', None, '일반어', '명사', 'I', None),
            ('아이', '외래어', '어휘', None, '아이', None, '일반어', '명사', 'i', None),
            ('제이', '외래어', '어휘', None, '제이', None, '일반어', '명사', 'J', None),
            ('제이', '외래어', '어휘', None, '제이', None, '일반어', '명사', 'j', None),
            ('케이', '외래어', '어휘', None, '케이', None, '일반어', '명사', 'K', None),
            ('케이', '외래어', '어휘', None, '케이', None, '일반어', '명사', 'k', None),
            ('엘', '외래어', '어휘', None, '엘', None, '일반어', '명사', 'L', None),
            ('엘', '외래어', '어휘', None, '엘', None, '일반어', '명사', 'l', None),
            ('엠', '외래어', '어휘', None, '엠', None, '일반어', '명사', 'M', None),
            ('엠', '외래어', '어휘', None, '엠', None, '일반어', '명사', 'm', None),
            ('엔', '외래어', '어휘', None, '엔', None, '일반어', '명사', 'N', None),
            ('엔', '외래어', '어휘', None, '엔', None, '일반어', '명사', 'n', None),
            ('오', '외래어', '어휘', None, '오', None, '일반어', '명사', 'O', None),
            ('오', '외래어', '어휘', None, '오', None, '일반어', '명사', 'o', None),
            ('피', '외래어', '어휘', None, '피', None, '일반어', '명사', 'P', None),
            ('피', '외래어', '어휘', None, '피', None, '일반어', '명사', 'p', None),
            ('큐', '외래어', '어휘', None, '큐', None, '일반어', '명사', 'Q', None),
            ('큐', '외래어', '어휘', None, '큐', None, '일반어', '명사', 'q', None),
            ('알', '외래어', '어휘', None, '알', None, '일반어', '명사', 'R', None),
            ('알', '외래어', '어휘', None, '알', None, '일반어', '명사', 'r', None),
            ('에스', '외래어', '어휘', None, '에스', None, '일반어', '명사', 'S', None),
            ('에스', '외래어', '어휘', None, '에스', None, '일반어', '명사', 's', None),
            ('티', '외래어', '어휘', None, '티', None, '일반어', '명사', 'T', None),
            ('티', '외래어', '어휘', None, '티', None, '일반어', '명사', 't', None),
            ('유', '외래어', '어휘', None, '유', None, '일반어', '명사', 'U', None),
            ('유', '외래어', '어휘', None, '유', None, '일반어', '명사', 'u', None),
            ('브이', '외래어', '어휘', None, '브이', None, '일반어', '명사', 'V', None),
            ('브이', '외래어', '어휘', None, '브이', None, '일반어', '명사', 'v', None),
            ('더블유', '외래어', '어휘', None, '더블유', None, '일반어', '명사', 'W', None),
            ('더블유', '외래어', '어휘', None, '더블유', None, '일반어', '명사', 'w', None),
            ('엑스', '외래어', '어휘', None, '엑스', None, '일반어', '명사', 'X', None),
            ('엑스', '외래어', '어휘', None, '엑스', None, '일반어', '명사', 'x', None),
            ('와이', '외래어', '어휘', None, '와이', None, '일반어', '명사', 'Y', None),
            ('와이', '외래어', '어휘', None, '와이', None, '일반어', '명사', 'y', None),
            ('지', '외래어', '어휘', None, '지', None, '일반어', '명사', 'Z', None),
            ('지', '외래어', '어휘', None, '지', None, '일반어', '명사', 'z', None),
        ]
data_ = set()

for idx, val in enumerate(data):
  data_.add(val['origin_lang'])

for idx, val in enumerate(data_alp):
  if val[8] not in data_:
    data.append({'origin_lang': val[8], 'pronun_list': val[0]})

In [ ]:
import re

for idx, val in enumerate(data):
  data[idx]['origin_lang'] = re.sub('[^a-zA-Z]', '', val['origin_lang']).strip()

# # 중복을 제거한 결과를 저장할 리스트
# filtered_data = []

# # 중복된 값을 저장하기 위한 set
# unique_origin_lang = set()

# for entry in data:
#     origin_lang = entry['origin_lang']
#     if origin_lang not in unique_origin_lang:
#         unique_origin_lang.add(origin_lang)
#         filtered_data.append(entry)

# print(filtered_data)


In [ ]:
!pip install jamo

In [ ]:
from jamo import h2j, j2hcj

def jamo(txt):
  return [_ for _ in j2hcj(h2j(txt))]


In [ ]:
src = []
trg = []

# for idx, val in enumerate(filtered_data):
#   src.append([val['origin_lang']])

# trg = [[char for word in wordlist['pronun_list'] for char in word] for wordlist in filtered_data]

for idx, val in enumerate(data):
  src.append([val['origin_lang']])

trg = [[char for word in wordlist['pronun_list'] for char in word] for wordlist in data]

In [ ]:
print(trg[-1])
print(src[-1])

['와', '이']
['y']


In [ ]:
korean_char = [char for word in trg for char in word]
korean_char_unique = list(sorted(set(korean_char)))


In [ ]:
## Ready for data Pre-Processing
space = [' ']
pad = ['<pad>']
_and = ['&']
# Prepare English Data
big = [chr(i) for i in range(ord('A'), ord('Z')+1)]
small = [chr(i) for i in range(ord('a'), ord('z')+1)]

english_letter_list = pad + big + small + space + _and

idx2english = dict(enumerate(english_letter_list, 0))
english2idx = {v:k  for k,v in idx2english.items()}


# Prepare Korean Data
consonants = [chr(letter) for letter in range(ord('가'), ord('힣')+1)]
# vowel = [chr(letter) for letter in range(ord('ㅏ'), ord('ㅣ')+1)]

korean_letter_list = pad + korean_char_unique +  space

# Make a mapping with index
idx2korean = dict(enumerate(korean_letter_list, 0))
korean2idx = {v: k for k, v in idx2korean.items()}

print(len(english_letter_list))
print(len(korean_letter_list))

55
904


In [ ]:
for idx, val in enumerate()

SyntaxError: ignored

In [ ]:
import copy

src2idx = []
src2idx = [[english2idx[char] for word in wordlist for char in word] for wordlist in src]


trg2idx = []
trg2idx = [[korean2idx[char] for word in wordlist for char in word] for wordlist in trg]

src2idx_ = []
trg2idx_ = []
for idx, value in enumerate(src2idx):
  if len(src2idx[idx]) <= 20:
      src2idx_.append(value)
      trg2idx_.append(trg2idx[idx])


src2idx = src2idx_
trg2idx = trg2idx_
num_10 = 0
num_20 = 0
num_30 = 0
num_40 = 0
num_40_over = 0
for idx, value in enumerate(src2idx):
  if len(src2idx[idx]) <= 10:
    num_10 += 1
  elif len(src2idx[idx]) <= 20:
    num_20 += 1
  elif len(src2idx[idx]) <= 30:
    num_30 += 1
  elif len(src2idx[idx]) <= 40:
    num_40 += 1
  elif len(src2idx[idx]) > 40:
    num_40_over += 1

print(f"num_10 : {num_10}, num_20 : {num_20}, num_30: {num_30}, num_40 : {num_40}, num_40_over : {num_40_over}")

src2idx_reverse = copy.deepcopy(src2idx) # 단어 벡터를 lstm에 거꾸로 집어넣었을 때, 정확도를 보기 위해서 만듬

max_len_src = max(len(src2idx_list) for src2idx_list in src2idx)
max_len_trg = max(len(trg2idx_list) for trg2idx_list in trg2idx)


print(max_len_src)
print(max_len_trg)

num_10 : 37995, num_20 : 25183, num_30: 0, num_40 : 0, num_40_over : 0
20
15


In [ ]:
def padding(st_list, max_length, is_trg):
  # if is_trg == True:
  for tmp_list in st_list:
    while len(tmp_list) < max_length:
      tmp_list.append(0)
  # else:
  #   for tmp_list in st_list:
  #     while len(tmp_list) < max_length + 2:
  #       tmp_list.append(0)

padding(src2idx, max_len_src, False)
padding(trg2idx, max_len_trg, True)

src_size = len(src2idx)
trg_size = len(trg2idx)

src2idx_tensorflow = src2idx
trg2idx_tensorflow = trg2idx

src2idx_tensorflow_reverse = src2idx_reverse # 역변환


In [ ]:
# 리스트 역

import numpy as np

X = src2idx_tensorflow_reverse
y = trg2idx_tensorflow
padding(X, max_len_src, False)
z = []
print(X[0])
print(len(X[0]))
for idx, val in enumerate(X):
  z.append(val[::-1])
X = z
X = np.array(X)
y = np.array(y)

print(X[:50])



[33, 27, 44, 33, 41, 51, 38, 31, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
20
[[ 0  0  0  0  0  0  0  0  0  0  0 45 31 38 51 41 33 44 27 33]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 31 38 33 44 27 33]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 31 46 35 40 34 27 33]
 [ 0  0  0  0  0  0  0  0  0  0 31 40 41 38 41 50 27 40 27 33]
 [ 0  0  0  0  0  0  0  0  0  0 33 40 35 46 46 31 40 44 27 33]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 46 46 31 40 44 27 33]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 40 35 41 40 27 33]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 35 40 44 27 33]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 34 45 35 40 44 27 33]
 [ 0  0  0  0  0  0  0  0  0  0 31 46 35 44 31 35 40 44 27 33]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 46 31 40 44 27 33]
 [ 0  0  0  0  0  0  0  0  0 44 31 42 27 42 46 31 40 44 27 33]
 [ 0  0  0  0  0  0  0  0  0  0  0 30 31 44 46 31 40 44 27 33]
 [ 0  0  0  0  0  0  0  0  0 31 30 35 39 27 35 30 41 30 27 33]
 [ 0  0  0  0  0  0  0  0  0 38 41 30 35 44 3

In [ ]:
# import numpy as np

# X = src2idx_tensorflow
# y = trg2idx_tensorflow

# X = np.array(X)
# y = np.array(y)


# print(y[:5])

# print(y.shape)


[[  1  25 574 447   0   0   0   0   0   0   0   0   0   0   0]
 [  1  43   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1  60 571 808   0   0   0   0   0   0   0   0   0   0   0]
 [  1  61 421 216   0   0   0   0   0   0   0   0   0   0   0]
 [  1  82 818   0   0   0   0   0   0   0   0   0   0   0   0]]
(59923, 15)


TypeError: ignored

In [ ]:
for idx, val in enumerate(korean2idx):
  if korean2idx[val] == 1:
    print(val)
  if korean2idx[val] == 25:
    print(val)
  if korean2idx[val] == 574:
    print(val)
  if korean2idx[val] == 447:
    print(val)

가
고
싸
쟈


In [ ]:
import tensorflow as tf
from keras.layers.rnn import bidirectional
from keras.utils import np_utils
import tensorflow as tf
from sklearn.model_selection import train_test_split
from keras.models import Sequential, load_model
from keras.layers import Dense, TimeDistributed, Activation, RepeatVector, Embedding, LSTM, Masking, Dropout

print(tf.__version__)

2.12.0


In [ ]:
from keras.layers.rnn import bidirectional
from keras.utils import np_utils
num_classes = len(korean_letter_list)
print(X.shape)
print(y.shape)
## Split train & test & validation set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.15)


# Parameters for the model and dataset
HIDDEN_SIZE = 200
BATCH_SIZE = 64
LAYERS = 2
MAX_EPOCHS = 100
EMBEDDING_OUTPUT_SIZE = 200
DROPOUT_RATE = 0.20


stop_monitor = 'val_accuracy'
stop_delta = 0.0005
stop_epochs = 12


# ## Build Model
import tensorflow as tf
from keras.models import Sequential, load_model
from keras.layers import Dense, TimeDistributed, Activation, RepeatVector, Embedding, LSTM, Masking, Dropout



print('Build Model...')

model = Sequential()

model.add(Embedding(
    input_dim=len(english_letter_list),  # 단어 갯수 + padding (1)
    output_dim=EMBEDDING_OUTPUT_SIZE,  # 출력 벡터
    input_length=X.shape[1],  # 입력 길이
    mask_zero = True
))

model.add(LSTM(HIDDEN_SIZE, return_sequences=True, input_shape=(X.shape[1], )))
model.add(LSTM(HIDDEN_SIZE))

model.add(RepeatVector(y.shape[1]))  # Maximum output length

for _ in range(LAYERS):
    model.add(LSTM(HIDDEN_SIZE, return_sequences=True))
    model.add(Dropout(DROPOUT_RATE))

model.add(TimeDistributed(Dense(len(korean_letter_list))))
model.add(Activation('softmax'))

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)


model.summary()
print('Done')

# Callbacks
from keras.callbacks import EarlyStopping, ModelCheckpoint



callbacks_list = [
    EarlyStopping(
        monitor=stop_monitor,
        min_delta=stop_delta,
        patience=stop_epochs,
        verbose=1,
        mode='auto',
    ),
    ModelCheckpoint(filepath="/content/drive/MyDrive/my_model_best.h5",
        monitor=stop_monitor,
        save_best_only=True,
        verbose=1,
        mode='auto',)
]
hist = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    batch_size=BATCH_SIZE,
    epochs=MAX_EPOCHS,
    verbose=1,
    callbacks=callbacks_list
)

## Visualize history
loss, acc = model.evaluate(X_test, y_test)


print()
print("Last Model: ")
print('Loss: %.2f' % loss)
print('Accuracy: %.2f' % acc)

import matplotlib.pyplot as plt

epochs = range(1, len(hist.history['accuracy']) + 1)
plt.plot(epochs, hist.history['loss'])
plt.plot(epochs, hist.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

model.save('/contetn/drive/MyDrive/my_model_word_temp.h5')


(63178, 20)
(63178, 15)
Build Model...
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 200)           11000     
                                                                 
 lstm (LSTM)                 (None, 20, 200)           320800    
                                                                 
 lstm_1 (LSTM)               (None, 200)               320800    
                                                                 
 repeat_vector (RepeatVector  (None, 15, 200)          0         
 )                                                               
                                                                 
 lstm_2 (LSTM)               (None, 15, 200)           320800    
                                                                 
 dropout (Dropout)           (None, 15, 200)           0         
                 

KeyboardInterrupt: ignored

In [ ]:
model.save('/content/my_model_reverse.h5')

In [ ]:
!pip install hangul_utils

INFO: pip is looking at multiple versions of hangul-utils to determine which version is compatible with other requirements. This could take a while.
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
# 모델 로드
model = tf.keras.models.load_model("/content/my_model_reverse.h5")



In [ ]:
import numpy as np
def eng2idx(str1):
  str2idx = [char for char in str1]
  str2idx1 = [english2idx[char] for char in str2idx]
  while len(str2idx1) < max_len_src:
    str2idx1.append(0)

  return [str2idx1]

from keras.models import load_model

def one_hot2idx(model, str):
  predic = model.predict(eng2idx(str))
  predic_char = predic[0][0]
  _idx2korean = []
  for idx, val in enumerate(predic[0]):
    max_index = np.argmax(val)
    _idx2korean.append(max_index)

  idx2korean_ = [idx2korean[idx] for idx in _idx2korean if idx != 0]

  return idx2korean_
print(one_hot2idx(model, "twice"))

1/1 [==============================] - 0s 42ms/step
['에', '키', '트']


In [ ]:
file_path = "/content/eng_source_alpha.txt"  # 실제 파일 경로로 바꿔주세요
lines = []

try:
    with open(file_path, "r", encoding="utf-8") as file:
        lines = [line.strip() for line in file.readlines()]
except FileNotFoundError:
    print("파일을 찾을 수 없습니다.")
except Exception as e:
    print("오류가 발생했습니다:", e)

print(lines)



['G', 'IOT', 'N', 'S', 'PC', 'SNS', 'KT', 'PD', 'PD', 'A', 'C', 'SF', 'KT', 'MBCFM', 'LG', 'IQ', 'USB', 'USB', 'C', 'KT', 'b', 'KBN', 'KT', 'LG', 'UFO', 'MC', 'c', 'kt', 'kt', 'KT', 'A', 'KT', 'KT', 'KT', 'DJ', 'DC', 'G', 'KT', 'N', 'KT', 'KT', 'KT', 'MBCFM', 'CGV', 'Classic', 'SIGNAL', 'CCM', 'TT', 'MBC', 'FM', 'SHE', 'A', 'Artist', 'FM', 'NEVER', 'LOVE', 'Rookie', 'BOMB', 'FM', 'Ko', 'Ko', 'Bop', 'FIVE', 'Marry', 'Me', 'MBC', 'UFC', 'Hello', 'EDM', 'J', 'E', 'FUTURE', 'qt', 'UCC', 'CCTV', 'KT', 'UN', 'EC', 'A', 'X', 'Y', 'TF', 'WTO', 'RMD', 'EC', 'A', 'S', 'MLB', 'CEO', 'COO', 'FX', 'IFOEXA', 'BC', 'KBO', 'MBC', 'KBO', 'WCDMA', 'GM', 'SM', 'YG', 'XP', 'NPT', 'CSI', 'NPT', 'SK', 'FBI', 'CIA', 'SKLG', 'WTO', 'CJ', 'WTO', 'CIA', 'FTA', 'FTA', 'SK', 'FTA', 'CT', 'MRI', 'PC', 'RSA', 'DSVD', 'TCI', 'GM', 'PC', 'PC', 'MS', 'PC', 'TI', 'X', 'IQ', 'LA', 'NGO', 'FBI', 'IT', 'BJ', 'USB', 'CD', 'PC', 'MIT', 'OLAP', 'AMR', 'TPO', 'KTX', 'LA', 'H', 'K', 'L', 'LSI', 'Q', 'V', 'yui', 'GM', 'E', 'UA'

In [ ]:
import numpy as np
def eng2idx(str1):
  str2idx = [char for char in str1]
  str2idx1 = [english2idx[char] for char in str2idx]
  str2idx2 = str2idx1[::-1]
  while len(str2idx2) < max_len_src:
    str2idx2.append(0)
  return [str2idx2]

from keras.models import load_model

def one_hot2idx(model, str):
  predic = model.predict(eng2idx(str))
  predic_char = predic[0][0]
  _idx2korean = []
  for idx, val in enumerate(predic[0]):
    max_index = np.argmax(val)
    _idx2korean.append(max_index)

  idx2korean_ = [idx2korean[idx] for idx in _idx2korean if idx != 0]

  return ''.join(idx2korean_)

# with open('/content/eng_source_result.txt', 'w') as file:
#     for item in lines:
#         result = one_hot2idx(model, item)
#         file.write(result + '\n')  # Write the result to the file

# print("Results saved to 'output.txt'")

print(one_hot2idx(model, "b"))
print(one_hot2idx(model, "ifoexa"))
print(one_hot2idx(model, "IFOEXA"))

# print(one_hot2idx(model, "jonna"))
# print(one_hot2idx(model, "fuck"))
# print(one_hot2idx(model, "you"))
# print(one_hot2idx(model, "bitch"))
# print(one_hot2idx(model, "mega"))
# print(one_hot2idx(model, "samsung"))
# print(one_hot2idx(model, "hyundai"))
# print(one_hot2idx(model, "homerunball"))
# print(one_hot2idx(model, "control"))
# print(one_hot2idx(model, "wori"))
# print(one_hot2idx(model, "once"))
# print(one_hot2idx(model, "twice"))
# print(one_hot2idx(model, "sexily"))
# print(one_hot2idx(model, "halabozi"))
# print(one_hot2idx(model, "multiheadattention"))
# print(one_hot2idx(model, "whitecotton"))
# print(one_hot2idx(model, "youmotherboom"))
# print(one_hot2idx(model, "sequencediagram"))
# print(one_hot2idx(model, "natural"))
# print(one_hot2idx(model, "language"))
# print(one_hot2idx(model, "processing"))
# print(one_hot2idx(model, "IRB"))
# print(one_hot2idx(model, "G"))
# print(one_hot2idx(model, "SNS"))
# print(one_hot2idx(model, "LOVE"))
# print(one_hot2idx(model, "MS"))
# print(one_hot2idx(model, "RMD"))
# print(one_hot2idx(model, "K"))
# print(one_hot2idx(model, "REMAP"))
# print(one_hot2idx(model, "K"))
# print(one_hot2idx(model, "POP"))
# print(one_hot2idx(model, "K POP"))
# print(one_hot2idx(model, "P"))
# print(one_hot2idx(model, "SIGNAL"))

1/1 [==============================] - 0s 37ms/step
더이유
1/1 [==============================] - 0s 34ms/step
아이피세
1/1 [==============================] - 0s 37ms/step
아이에프아이에에에에이


In [ ]:
!pip install eng-to-ipa

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 14.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for eng-to-ipa: filename=eng_to_ipa-0.0.2-py3-none-any.whl size=2822607 sha256=1bb0a4043643737509dbe3b0051ebb5fb627792588378c6f4881d7566a2eaba3
  Stored in directory: /root/.cache/pip/wheels/5b/ab/07/fe6722f710d8ef8bd0ccb4eb689ef96f5552f3fc0c80c1aa9c
Successfully built eng-to-ipa


In [ ]:
import eng_to_ipa as ipa

apple = ipa.convert("")
print(apple)

kaiti*
